# Generated by Django 5.1.1 on 2024-11-21 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_invitee_eventinvite_invitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventinvite',
            old_name='invited',
            new_name='invitee',
        ),
    ]
