# Generated by Django 5.1.1 on 2024-11-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_invited_eventinvite_invitee'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EventInvite',
        ),
    ]
