# Generated by Django 5.1.1 on 2024-11-21 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_delete_eventinvite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='eventtype',
            field=models.CharField(choices=[('Public', 'Public'), ('Private', 'Private')], default='Public', max_length=18),
        ),
    ]
